# Generated by Django 3.0.5 on 2020-04-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='bpub_title',
            new_name='bpub_date',
        ),
    ]
